version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=notes_app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root1234
    volumes:
      - /data/mysql
    ports:
      - 3333:3306
    container_name: mysql-db

  spring-demo-app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot-app
    container_name: spring-demo-app