version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: notes_app
    ports:
      - "3307:3307"
    networks:
      mysql-net:

  spring-demo:
    container_name: spring-demo
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/notes_app?autoReconnect=true&useSSL=false
    depends_on:
      - mysqldb
    networks:
      mysql-net:
    restart: on-failure

networks:
  mysql-net: